### ISSUE TITLE
Temas Sugeridos

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/OpenDevUFCGBlog#1]
Segue uma lista de temas sugeridos para publicação:

- [ ] Vue
- [ ] React
- [ ] Angular
- [ ] npm
- [ ] NodeJS
- [ ] Mongo
- [ ] GraphQl
- [ ] CSS3 
- [x] HTML5
- [ ] Flask
- [ ] Webpack
- [ ] ES7
- [x] Jest
- [ ] Docker
- [ ] Nock
- [x] Mocha + Chai

**Comment by juliobguedes** [comment]
Posso escrever sobre Jest, Sinon, Mocha e Chai. Todos são frameworks de teste em JS

**Comment by juliobguedes** [comment]
Sugiro também:
* [ ] JUnit
* [ ] Mockito
* [ ] Next.js
* [ ] Nuxt.js (maybe junto com Next.js?)
* [ ] APIs Restful
* [ ] Programação Funcional
* [ ] Processamento de Imagens
* [ ] Regressão Linear
* [ ] Machine Learning
* [ ] Redes Neurais

**Comment by JuanBarros2** [comment]
Concordo com a sugestão, @juliobguedes . Coloquei esses por ser mais populares, mas seria top se tivesse pessoas pra fazer tbm. Posso marcar o do Jest e do Mocha + Chai pra ti?

**Comment by JoseRenan** [comment]
Como os posts são pequenos, eu acho que seria bom quebrar mais pra delegar algumas explicações do posto atual pra algum post passado, por exemplo, ter um post sobre testes mais teórico mostrando alguns tipos e técnicas de teste, tipo mocks, stubs, teste de interface, teste de carga, um resumão e depois em um de sinon, por exemplo não vai precisar explicar muito sobre mock, em um de nock tb, etc, ou então fazer uma série sobre técnicas de teste mostrando cada tipo ou técnica separadamente com exemplos na prática

**Comment by juliobguedes** [comment]
> Concordo com a sugestão, @juliobguedes . Coloquei esses por ser mais populares, mas seria top se tivesse pessoas pra fazer tbm. Posso marcar o do Jest e do Mocha + Chai pra ti?

yep

**Comment by LukeHxH** [comment]
Eu posso escrever sobre JUnit.

**Comment by fanny** [comment]
Sugiro também:
- [ ] D3
- [ ] Vega-Lite
- [ ] Analise de dados, pode descritiva msm inicilamente(pandas, numpy..)

**Comment by fanny** [comment]
> Como os posts são pequenos, eu acho que seria bom quebrar mais pra delegar algumas explicações do post atual pra algum post passado, por exemplo, ter um post sobre testes mais teórico mostrando alguns tipos e técnicas de teste, tipo mocks, stubs, teste de interface, teste de carga, um resumão e depois em um de sinon, por exemplo não vai precisar explicar muito sobre mock, em um de nock tb, etc, ou então fazer uma série sobre técnicas de teste mostrando cada tipo ou técnica separadamente com exemplos na prática

Acho mt valido, tem uma overview primeiro e depois um tutorials

Show de bola

**Comment by JuanBarros2** [comment]
É @JoseRenan , tava pensando em montar de um jeito que desse pra entender, se você já sabe aquele universo e se não souber que tenha conteúdo para dar base também.

**Comment by thayannevls** [comment]
Sugiro React Hooks
