### ISSUE TITLE
[NOVO] Testes em Javascript: Conceitos iniciais

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/OpenDevUFCGBlog#3]
Descrição: Durante o desenvolvimento de aplicações, testes são extremamente necessários para assegurar o funcionamento correto da aplicação durante seu uso e evolução. Diferente do que alguns pensam, aplicações web e mobile também necessitam de testes para garantir qualidade ao produto. Dessa forma, essa proposta busca introduzir alguns conceitos de testes, para então descrever como realizar testes em aplicações Web e Mobile utilizando alguns dos mais comuns frameworks de teste, como Mocha, Chai, Sinon e Jest.

- [x] Me interesso por escrever um post sobre o tema acima. Estou ciente que esse post
será publicado na organização da OpenDevUFCG na plataforma [dev.to](https://dev.to/), me
creditando a autoria pelo conteúdo criado nesse post e ficará disponível no presente 
repositório. Também estou ciente que a organização publicará posts propagando minha
publicação em redes sociais, dando visibilidade ao meu post.

**Comment by JRobsonJr** [comment]
Oi, @juliobguedes! Acabei de subir um CONTRIBUTING.md para guiar o desenvolvimento do seu post: https://github.com/OpenDevUFCG/OpenDevUFCGBlog/blob/master/CONTRIBUTING.md

Qualquer dúvida, pode entrar em contato!
