### ISSUE TITLE
[NOVO] Contribuindo para comunidades Open Source com Github

### ISSUE THREAD

**Issue by lucasmedeiros** [OpenDevUFCG/OpenDevUFCGBlog#4]
**Descrição**: Uma porta de entrada para pessoas que planejam começar a fazer contribuições para organizações Open Source, falando um pouco sobre o que é o Github (uma visão geral sobre o que é a plataforma, sem um aprofundamento muito grande em detalhes técnicos) e como possibilita o crescimento de comunidades open source. Além disso, este post mostra também como ficar atento ao surgimento de novas oportunidades de contribuição em projetos.

- [x] Me interesso por escrever um post sobre o tema acima. Estou ciente que esse post
será publicado na organização da OpenDevUFCG na plataforma [dev.to](https://dev.to/), me
creditando a autoria pelo conteúdo criado nesse post e ficará disponível no presente 
repositório. Também estou ciente que a organização publicará posts propagando minha
publicação em redes sociais, dando visibilidade ao meu post.

**Comment by JuanBarros2** [comment]
Na parte:

> ...uma funcionalidade que tem por objetivo a ampliação do alcance dos projetos open source.

Acho que fica muito restritivo visto que é possível visualizar projetos em geral (ex: projeto fechado que foi compartilhado com você).

**Comment by JuanBarros2** [comment]
> Essa requisição é a pull request, que será revisada um maintainer

Seria _por um maintainer_?

**Comment by JRobsonJr** [comment]
Oi, @lucasmedeiros! Acabei de subir um CONTRIBUTING.md para guiar o desenvolvimento do seu post: https://github.com/OpenDevUFCG/OpenDevUFCGBlog/blob/master/CONTRIBUTING.md

Qualquer dúvida, pode entrar em contato!
