### ISSUE TITLE
[NOVO] [Introdução][Ciência de Dados]

### ISSUE THREAD

**Issue by hadrizia** [OpenDevUFCG/OpenDevUFCGBlog#6]
Por favor, utilize o seguinte template para sugerir um novo post:

# Introdução à Ciência de Dados
Pretendo trazer um post com uma introdução à área de ciência de dados, uma das áreas atualmente mais promissoras de computação.

**Descrição**

O post está dividido nos seguintes tópicos:
1. O que é Ciência de Dados: defino um conceito para a área explicando o que é ciência, o que são dados e o que é ciência de dados;
2. **[WIP]** Principais áreas - engenharia de dados, ciência de dados descritiva, ciência de dados descritiva: Apresento cada uma das três subáreas principais, com exemplos que acho bacanas.
3. **[TODO]** O que você precisa saber para começar na área: Pretendo apresentar alguns conteúdos relevantes para quem deseja saber + as disciplinas disponíveis no curso para quem tiver interesse em cada uma das áres. 

**Sugestões são maaais que bem vindas :D**

- [x] Me interesso por escrever um post sobre o tema acima. Estou ciente que esse post
será publicado na organização da OpenDevUFCG na plataforma [dev.to](https://dev.to/), me
creditando a autoria pelo conteúdo criado nesse post e ficará disponível no presente 
repositório. Também estou ciente que a organização publicará posts propagando minha
publicação em redes sociais, dando visibilidade ao meu post.

**Comment by JRobsonJr** [comment]
Oi, @hadrizia! Acabei de subir um CONTRIBUTING.md para guiar o desenvolvimento do seu post: https://github.com/OpenDevUFCG/OpenDevUFCGBlog/blob/master/CONTRIBUTING.md

Qualquer dúvida, pode entrar em contato!
